spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entry-auth?createDatabaseIfNotExist=true
    username: root
    password: Hoanglekha@123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9002
SECRET-KEY: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
