eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entry-product?createDatabaseIfNotExist=true
    username: root
    password: Hoanglekha@123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9003
